services:
  movie-manager-app:
    container_name: movie-manager-app
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      NODE_ENV: prod
      DATABASE_URL: ${DATABASE_URL_DOCKER}
    networks:
      - nestjs
  db:
    container_name: movie-manager-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs

volumes:
  postgres_data:
networks:
  nestjs: